run_test:
	nextflow run workflow.nf -resume -with-docker chambm/pwiz-skyline-i-agree-to-the-vendor-licenses

run_data:
	#nextflow run workflow.nf -resume -with-docker chambm/pwiz-skyline-i-agree-to-the-vendor-licenses --inputspectra "data/steve_barnes/pos/*.mzXML"
	nextflow run workflow.nf -resume -with-docker chambm/pwiz-skyline-i-agree-to-the-vendor-licenses --inputspectra "data/steve_barnes/neg/*.mzXML"

	